### ISSUE TITLE
I don't get how to set up it

### ISSUE THREAD

**Issue by PalePyth** [Baughn/PrometheusIntegration#1]
_Install docker on your server, by whichever means._
Where exactly?

_Run the following commands._
In cmd?

Why shall I install it on client-side?

I don't get how to set up Nginx as a reverse proxy for Promdash. What file I should paste the code?

Thanks in advance.

**Comment by Baughn** [comment]
On the machine. If you're on Debian, use "sudo apt-get install docker.io"

**Comment by PalePyth** [comment]
No details :(

**Comment by Baughn** [comment]
If you don't know how to run apt-get, then I don't think I can help you. Look up the documentation for your Linux distribution.

**Comment by PalePyth** [comment]
Wait, is it for Linux only?

**Comment by Baughn** [comment]
Docker is, yes. Prometheus... not exactly, but I don't know how to set it up on Windows. YMMV.

There'll be a self-contained version of this eventually.

**Comment by PalePyth** [comment]
It's better to notice others it's only for Linux.
