### ISSUE TITLE
Possible to get an update for this that will support 1.11.2 and 1.12 in the future?

### ISSUE THREAD

**Issue by Electrofried** [Baughn/PrometheusIntegration#3]
title.

Thanks :)

**Comment by Baughn** [comment]
Oh, definitely. Look for a release sometime this weekend.

**Comment by Inrixia** [comment]
Hey, sorry to bring this back up. We host a variety of servers and it would be really helpful if this was to be updated to 1.11 sometime. Do you ever plan to? Is there anything we could do to convince you to?

**Comment by Baughn** [comment]
I have a really bad tendency to say I'll work on P-I and then not do it, yeah...

At the moment I actually *can't*, I have some issues wrt. intellectual property assignment, but I expect that to be a temporary problem. As it stands... the mod is actually trivial. You could probably port it yourself if you strongly want it.

I won't be able to accept a pull request, but that's a temporary state of affairs.

**Comment by Inrixia** [comment]
Ok, thanks :) we were considering doing that anyway. Good luck for your assignment.
